# Generated by Django 5.1.3 on 2024-11-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='projects/files/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/files/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/images/'),
        ),
    ]
