# Generated by Django 5.1.3 on 2024-11-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='monograph',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='author',
            new_name='user',
        ),
    ]
