# Generated by Django 5.1.3 on 2024-11-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_remove_project_author_remove_project_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
